name: deflowpp

target:
  _target_: src.models.DeFlowPP
  decoder_option: gru # choices: [linear, gru]
  num_iters: 2
  voxel_size: ${voxel_size}
  point_cloud_range: ${point_cloud_range}
  num_frames: ${num_frames}

val_monitor: val/Dynamic/Mean