name: fastnsf

target:
  _target_: src.models.FastNSF
  filter_size: 128
  act_fn: relu
  layer_size: 8
  itr_num: 5000
  lr: 8e-3
  min_delta: 5e-5
  grid_factor: 10
  init_weight: True
  early_patience: 10 # default is 10, set 30 to get better results
  point_cloud_range: [-51.2, -51.2, -3, 51.2, 51.2, 3]
  
val_monitor: val/Dynamic/Mean
iter_only: True